{"version":1,"resource":"file:///home/birkhoff/Lab/python/exo5/exceptions_generator.py","entries":[{"id":"seTG.py","timestamp":1651041198497},{"id":"KZXR.py","timestamp":1651041317277},{"id":"VZkr.py","timestamp":1651041360068},{"id":"8K1C.py","timestamp":1651041446862},{"id":"gzK6.py","timestamp":1651041528044},{"id":"OaSC.py","timestamp":1651041580222},{"id":"dj8H.py","timestamp":1651041612677},{"id":"dPkk.py","timestamp":1651041653064},{"id":"lHLJ.py","timestamp":1651041676449},{"id":"aFDi.py","timestamp":1651041691002},{"id":"ElXT.py","timestamp":1651041718336},{"id":"MzNr.py","timestamp":1651041773457},{"id":"EtUH.py","timestamp":1651041792680}]}